feat. ShareIt добавление репозиториев - реализация комментариев и бро…
MorgunovAndreyV/java-shareit pull request #3
Opened 2024-02-25 10:47 UTC by MorgunovAndreyV

…нирования

2024-02-26 09:19 UTC, avlin87 requested changes
Привет, Андрей,
Работа выглядит хорошо - автоматические проверки проходят успешно,
Смотри, пожалуйста, комментарии ниже.

2024-02-26 09:19 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/BookingStatus.java
> +    WAITING, APPROVED, REJECTED
`можно лучше`
Читаемость кода можно повысить записав каждое значение на отдельной строке.

2024-02-26 09:19 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/BookingDbStorage.java
> +public class BookingDbStorage implements BookingStorage {
Этот класс выглядит лишним.
Структура нашего приложения подразумевается: `Controller - Service - Repository`
Роль Repository выполняет BookingRepository. В этом и есть прелесть Spring framework, что можно сократить количество кода.

Удали, пожалуйста, класс BookingDbStorage и интерфейс BookingStorage.

2024-02-26 09:19 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    private final BookingStorage bookingStorage;
Замени, пожалуйста, BookingStorage на BookingRepository.

2024-02-26 09:19 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    @Autowired
`@RequiredArgsConstructor` сгенерирует конструктор для инициализации полей
- userService
- itemService

`@Autowired` подразумевает инициализацию поля напрямую. Рекомендуется инициализировать поля используя конструктор. Удали, пожалуйста, эту аннотацию над полями класса.

2024-02-26 09:19 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    private void bookingDataValidations(BookingDto bookingDto, Long userId) {
Именование переменных - существительные.
Именование методов - глагол, так как метод должен что-то делать. 
Переименуй, пожалуйста, метод в `validateBookingData` или что-то подобное.

2024-02-26 09:19 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/BookingStorage.java
> +public interface BookingStorage {
Удали, пожалуйста, этот интерфейс.

2024-02-26 09:19 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/booking/State.java
> +    ALL, CURRENT, FUTURE, WAITING, REJECTED, PAST
`можно лучше`
Читаемость кода можно повысить записав каждое значение на отдельной строке.

2024-02-26 09:19 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/item/CommentDbStorage.java
> +public class CommentDbStorage implements CommentStorage {
Используй, пожалуйста, напрямую CommentRepository.
CommentDbStorage и CommentStorage лучше удалить.

2024-02-26 09:19 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/item/ItemDbStorage.java
> +public class ItemDbStorage implements ItemStorage {
Так же используй, пожалуйста, ItemRepository.
Эти классы лучше удалить ItemDbStorage и ItemStorage.

2024-02-26 09:19 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
>  public class InMemoryUserStorage implements UserStorage {
Оставь, пожалуйста, только UserRepository.

2024-02-26 20:43 UTC, MorgunovAndreyV commented on src/main/java/ru/practicum/shareit/booking/BookingStatus.java
> +    WAITING, APPROVED, REJECTED
,Александр, привет!

Готово

2024-02-26 20:45 UTC, MorgunovAndreyV commented on src/main/java/ru/practicum/shareit/booking/BookingDbStorage.java
> +public class BookingDbStorage implements BookingStorage {
Убрал слой с интерфейсами xStorage и классы, их использующие.
Прошелся по сервисам для Comment, User,Item, Booking

2024-02-26 20:45 UTC, MorgunovAndreyV commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    private final BookingStorage bookingStorage;
Готово

2024-02-26 20:45 UTC, MorgunovAndreyV commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    @Autowired
Аннотацию убрал

2024-02-26 20:46 UTC, MorgunovAndreyV commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    private void bookingDataValidations(BookingDto bookingDto, Long userId) {
Выполнено для аналогичных методов в других сущностях.
Проверил именование методов вообще - вроде все правильно

2024-02-26 20:46 UTC, MorgunovAndreyV commented on src/main/java/ru/practicum/shareit/booking/BookingStorage.java
> +public interface BookingStorage {
Готово

2024-02-26 20:46 UTC, MorgunovAndreyV commented on src/main/java/ru/practicum/shareit/booking/State.java
> +    ALL, CURRENT, FUTURE, WAITING, REJECTED, PAST
Готово

2024-02-26 20:46 UTC, MorgunovAndreyV commented on src/main/java/ru/practicum/shareit/item/CommentDbStorage.java
> +public class CommentDbStorage implements CommentStorage {
Готово

2024-02-26 20:46 UTC, MorgunovAndreyV commented on src/main/java/ru/practicum/shareit/item/ItemDbStorage.java
> +public class ItemDbStorage implements ItemStorage {
Готово

2024-02-26 20:46 UTC, MorgunovAndreyV commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorage.java
>  public class InMemoryUserStorage implements UserStorage {
Готово

2024-02-27 21:14 UTC, avlin87 approved these changes
Все хорошо, работу принимаю.

2024-02-29 18:25 UTC, merged