feat. ТЗ-15. Заявки на вещи + тестирование
MorgunovAndreyV/java-shareit pull request #4
Opened 2024-03-08 14:05 UTC by MorgunovAndreyV

2024-03-09 17:54 UTC, avlin87 requested changes
Привет, Андрей,
Хорошая работа, смотри, пожалуйста, комментарии ниже.

2024-03-09 17:54 UTC, avlin87 commented on src/main/java/ru/practicum/shareit/config/ContextConfig.java
> +public class ContextConfig {
Эта конфигурация выглядит излишней.
Удали, пожалуйста, этот класс.

Аннотация `@SpringBootApplication` на классе `ShareItApp` сама запустит сканирование компонент в пакете.
`@ComponentScan` подошел бы если бы у нас было несколько пакетов и мы бы хотели отсканировать конкретный.

Пример:
```
@SpringBootApplication
@ComponentScan("package.package")
public class ShareItApp {
    public static void main(String[] args) {
        SpringApplication.run(ShareItApp.class, args);
    }
}

```

2024-03-09 17:54 UTC, avlin87 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    ObjectMapper mapper;
`Можно лучше`
Переменные тестового класса тоже можно сделать приватными, так же как у тебя приватны статические переменные ниже.
В этом плане лучше всего соблюдать однообразность.

Статические переменные принято располагать в классе первыми, уже после них нестатические.

2024-03-09 17:54 UTC, avlin87 commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIntTest.java
> +    void testGetBookingsFilteredByStateALL() {
`Можно лучше`
В этом классе у нас получились достаточно длинные тесты.
Хорошо бы придерживаться следующих принципов при написании Unit тестов:
- Тест проверяет что-то одно.
- Структура тестов:
- - Подготовка даты
- - Выполнение тестируемой операции
- - Assertions

Если нарушаем структуру - то падает читаемость тестов, становится сложнее разобраться "что не так", когда внесли изменение в логику и падает тест, который проверяет сразу несколько аспектов нашей логики.

По этому совет: разделить такие тесты на отдельные, если возможно.

2024-03-09 17:54 UTC, avlin87 commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +        Mockito
`Можно лучше`
обычно первый вызываемый метод в цепочке не переносят

```
        Mockito.when(userService.getUserById(Mockito.anyLong()))
                .thenReturn(testUserOwner2);
```

2024-03-09 23:13 UTC, MorgunovAndreyV commented on src/test/java/ru/practicum/shareit/booking/BookingServiceIntTest.java
> +    void testGetBookingsFilteredByStateALL() {
Готово. Разделил крупные тесты по более узкому контексту

2024-03-09 23:13 UTC, MorgunovAndreyV commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +        Mockito
Исправлено

2024-03-09 23:14 UTC, MorgunovAndreyV commented on src/main/java/ru/practicum/shareit/config/ContextConfig.java
> +public class ContextConfig {
Александр, привет!
Это были мои попытки настроить интеграционные тесты...
Посмотрел не туда - в интеграционных тестах использовал не совсем подходящую для Boot нотацию (@SpringJUnitConfig), а с ней пришлось что-то мудрить с конфигурацией контекста. Получилось в работающем, но кривом виде.
Посмотрел внимательнее на описание нотаций для интеграционных тестов - добавил корректную нотацию - @SpringBootTest вместо @SpringJUnitConfig. Конфигурационный класс удалил.

После добавления @SpringBootTest все интеграционные тесты падали друг за другом, кроме первого. Был конфликт на уровне входных данных каждого тестового интеграционного класса - как я понял, с новой нотацией контекст и инстанс бд стали неизменными - данные от предыдущих тестов конфликтовали с последующими. 
Попробовал нотацию @DirtiesContext - вроде она как раз помогает при вызовы дропать контекст в нужные моменты. Получилось поведение, которое мне удалось настроить в предыдущем варианте с кривой нотацией инициализации теста. Если ок - могу оставить, либо тогда подумать над дропом данных на уровне методов отдельных тестов

2024-03-09 23:14 UTC, MorgunovAndreyV commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    ObjectMapper mapper;
Готово

2024-03-10 06:25 UTC, avlin87 approved these changes
Работу принимаю.

2024-03-12 17:53 UTC, merged